table TitleCountries
	lineageTag: 6f05efff-16af-4b99-bd19-2a6dc10042b8

	column show_id
		dataType: string
		lineageTag: 9c546810-b465-4bac-9446-443332626193
		summarizeBy: none
		sourceColumn: show_id

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 5a0fd1d5-be39-4af8-99dd-1847ef65670d
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column country_name
		dataType: string
		lineageTag: 62c0aef2-fdab-4561-a7be-0c7f57d01aaf
		summarizeBy: none
		sourceColumn: country_name

		annotation SummarizationSetBy = Automatic

	partition TitleCountries = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\dell\Documents\netflix-content-analysis\data\processed\netflix_countries.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"show_id", type text}, {"type", type text}, {"country_name", type text}})
				in
				    Typed

	annotation PBI_ResultType = Table

